export const DAY_PRESS_SELECTED = 'DAY_PRESS_SELECTED';
export const GET_LIST_BANNER = 'GET_LIST_BANNER';
export const UPDATE_STATE = 'UPDATE_STATE';
export const GET_LIST_SERVICE = 'GET_LIST_SERVICE';
export const SET_LOADING = 'SET_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT'
export const GET_LIST_SCHEDULE = 'GET_LIST_SCHEDULE'
export const GET_SCHEDULE_WAITING = 'GET_SCHEDULE_WAITING'
export const GET_SPA = 'GET_SPA'
export const GET_LIST_AGENCY = 'GET_LIST_AGENCY'
export const KEY_DOWN = 'KEY_DOWN'




